version: '3'
services:
  api:
    build:
      context: src/api
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Update 'VARIANT' to pick a .NET Core version: 2.1, 3.1, 5.0
        VARIANT: 5.0
        # Options
        INSTALL_NODE: 'false'
        NODE_VERSION: 'lts/*'
        INSTALL_AZURE_CLI: 'false'
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - .:/workspace:cached
      # - ${HOME}/.zsh_history:/home/vscode/.zsh_history:cached
      # - ${HOME}/.config/.dotfiles/zsh/.zshrc:/home/vscode/.zshrc:cached
      # - ${HOME}/.config/.dotfiles/zsh/.p10k.zsh:/home/vscode/.p10k.zsh:cached
      # - ${HOME}/.oh-my-zsh/custom:/home/vscode/.oh-my-zsh/custom:cached
      - ${HOME}/.microsoft/usersecrets:/home/vscode/.microsoft/usersecrets:cached
      - api-extensions-data:/home/vscode/.vscode-server/extensions
    environment:
      MACHINE_TYPE: computer
      INSTALL_DOTNET_TOOLS: "true"
      AppSettings__Token: unmoving-dole-outskirts-debunk
      AppSettings__Host: localhost
      AppSettings__Port: 3306
      AppSettings__DbUser: librarydb
      AppSettings__DbPassword: Password123
      AppSettings__DatabaseName: librarydb

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  spa:
    build:
      context: src/spa
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - .:/workspace:cached
      - ~:${HOME}:cached
      - spa-extensions-data:/home/node/.vscode-server/extensions

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: librarydb
      MYSQL_USER: librarydb
      MYSQL_PASSWORD: Password123

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mariadb-data:
  api-extensions-data:
  spa-extensions-data:
