version: '3.4'

services:
  materiallmsspa:
    image: materiallmsspa
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
